# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-27 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_day', models.DateTimeField()),
                ('ticket_number', models.IntegerField()),
                ('group_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_base.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='starosta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_base.Student'),
        ),
    ]
