# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-27 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_day',
            field=models.DateField(),
        ),
    ]
